# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_dish',
            name='display_name',
            field=models.CharField(default='Default Display Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='side_dish',
            name='display_name',
            field=models.CharField(default='Default Display Name', max_length=100),
            preserve_default=False,
        ),
    ]
