# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170302_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_order',
            name='side',
            field=models.IntegerField(default=0),
        ),
    ]
