# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_meal_order_side'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal_order',
            old_name='side',
            new_name='sides',
        ),
    ]
