# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170302_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_dish',
            name='price',
            field=models.IntegerField(default=700),
        ),
        migrations.AlterField(
            model_name='side_dish',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
