# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170303_0904'),
        ('home', '0008_auto_20170302_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='home.Meal_Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.User')),
            ],
        ),
    ]
