# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170303_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_order',
            name='sides',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_orders', to='home.Side_Dish'),
        ),
    ]
