# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170305_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_order',
            name='sides',
            field=models.CharField(max_length=200),
        ),
    ]
