# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170305_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
